### ISSUE TITLE
Adding people to the organization

### ISSUE THREAD

**Issue by livviest** [J-Gravity/j-gravity#2]
Leave a comment and ping me on Slack to be added to the repository.

After the invite is sent, go to https://github.com/J-Gravity and click the links to accept.

**Comment by coder-guy22296** [comment]
*leaves comment*

**Comment by giacope** [comment]
Leave a comment

**Comment by lordmalvern** [comment]
http://mancat.club/

**Comment by izcet** [comment]
Why

**Comment by lordmalvern** [comment]
It's my comment on life

**Comment by izcet** [comment]
No I'm commenting to join
